

__CONFIG _FOSC_INTRCIO & _WDTE_ON & _PWRTE_OFF & _MCLRE_ON & _BOREN_ON & _CP_OFF & _CPD_OFF

org H'0000'
GOTO INIT


INIT:    
	BSF STATUS, 5 ; BANK 1
	MOVLW 0x02    ; RA2 INPUT
    MOVWF TRISA  
	CLRF TRISC    ;PORTC OUTPUT

    CLRF ANSEL    ; ANALOG FUNCTIONS DISABLED
    MOWF 0x07     ; COMPARATORS OFF
    MOVLW CMCON    

	BCF STATUS, 5 ; BANK 0
	CLRF PORTA    ; INIT PORTA
	CLRF PORTC    ; INIT PORTC

main:
    CALL Check_SW_2 ; POLLS TO CHECK BUTTON PRESS
    BTFSC PORTA, 2  ; CHECK BUTTON PRESS
    BCF PORTC, 1
    GOTO main

Check_SW:
    BTFSC PORTA, 2
    RETURN
    BTFSC PORTA, 2 ; TOGGLE BUTTON CHECK CONDITION
    CALL DEBOUNCE
    MOVLW 0x12     ; TURN ON RC1 and RC4
    XORWF PORTC, 1
    CALL toggle_delay ; PWM_DELAY
    RETURN

DEBOUNCE:                       ;40.54ms
    MOVLW d'255'
    MOVWF 0x30
    MOVLW d'53'
    MOVWF 0x31
DEBNC_DLY:
    DECFSZ 0x30, 1
    GOTO DEBNC_DLY
    DECFSZ 0x31
    GOTO DEBNC_DLY
    RETURN

toggle_delay:                   ;10ms
    MOVLW d'255'
    MOVWF 0x40
    MOVLW d'13'
    MOVWF 0x41
TOGGLING:
    DECFSZ 0x40, 1
    GOTO TOGGLING
    DECFSZ 0x41
    GOTO TOGGLING
    RETURN
 
 end


